### ISSUE TITLE
Jenkins Pipeline should not echo out $AWS_SECRET_ACCESS_KEY

### ISSUE THREAD

**Issue by davekerr95** [CiaraBWalsh/Jenkins_tutorial#1]
https://github.com/CiaraBWalsh/Jenkins_tutorial/blob/9e4488d7b6054d09315fc6e6597ca7cd2d9f6329/Jenkinsfile#L18

Looks like this needs to be fixed, Could cause a leakage of credentials if people are using this tutorial

**Comment by davekerr95** [comment]
@CiaraBWalsh Any update on this issue, We just got hacked.

**Comment by CiaraBWalsh** [comment]
Will update this asap, pretty bad security vulnerability there 😣

**Comment by CiaraBWalsh** [comment]
Fixed issue
